#!/usr/bin/env python
# license removed for brevity
import rospy
from geometry_msg.msg import Twist
# from std_msgs.msg import String
print("TEST")

def straight_line():
    print("TEST2")
    vel = Twist
    vel.linear.x =0
    vel.linear.y =0
    vel.linear.z =0
    vel.angular.x = 0
    vel.angular.y = 0
    vel.angular.z = 0
    pub = rospy.Publisher('/cmd_vel', Twist, queue_size=10)
    rospy.init_node('/cmd_vel', anonymous=True)
    rate = rospy.Rate(1) # 10hz
    for i in range(20):
        vel.linear.x = i
        rospy.loginfo(vel)
        pub.publish(vel)
        rate.sleep()

if __name__ == '__main__':
    try:
        straight_line()
    except rospy.ROSInterruptException:
        pass
